//
//  CharacterPickerView.swift
//  Abelito
//
//  Created by Karyna Budi Sanjaya on 19/05/25.
//

import SwiftUI

struct CharacterPickerView: View {
    
    @ObservedObject var viewModel: ProfileViewModel
    @Binding var selectedCharacterIndex: Int
    @Binding var selectedSkill: Skill?
    @Binding var showSkillDetail: Bool
    @Binding var path: NavigationPath

    
    var body: some View {
        VStack() {
            let character = viewModel.characters[selectedCharacterIndex]
            
            Text("All images were generated by AI.")
                .font(.custom("FOT-Reggae Std B", size: 8))
            
            ScrollView(.horizontal) {
                HStack(spacing: -80) {
                    ForEach(viewModel.characters.indices, id: \.self) { index in
                        VStack {
                            // Image(viewModel.profile.skins[index].thumbnail)
                            
                            
                            Image(viewModel.characters[index].skin.thumbnail)
                                .resizable()
                                .scaledToFit()
                                .frame(width: 160, height: 200)
                                .containerRelativeFrame(.horizontal, count: 1, spacing: 4)
                                .scaleEffect(selectedCharacterIndex == index ? 1.0 : 0.8)
                                .opacity(selectedCharacterIndex == index ? 1.0 : 0.4)
                                .animation(.easeInOut(duration: 0.1), value: selectedCharacterIndex)
                            Text(viewModel.characters[index].skin.name)
                                .font(selectedCharacterIndex == index ?                         .custom("FOT-Reggae Std B", size: 16) :                         .custom("FOT-Reggae Std B", size: 12)
)
                                .opacity(selectedCharacterIndex == index ? 1.0 : 0.4)
                                .animation(.easeInOut(duration: 0.1), value: selectedCharacterIndex)
                        }
                        .id(index)
                    }
                }
                .scrollTargetLayout()
            }
//            .scrollPosition(id: $selectedCharacterIndex)
            .contentMargins(20, for: .scrollContent)
            .scrollTargetBehavior(.viewAligned)
            
            Button(action: {
//                path.append(Route.journey)
            }) {
                Text("Get To Know")
                    .font(.headline)
                    .foregroundColor(.white)
                    .padding()
                    .background(character.accentColor)
                    .cornerRadius(20)
            }
        }
        .padding()
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(
            LinearGradient(
                gradient: Gradient(colors: [.black.opacity(0.6), .accentColor.opacity(0.0)]),
                startPoint: .trailing,
                endPoint: .leading
            )
        )
    }
}

#Preview {
    CharacterPickerView(viewModel: ProfileViewModel(), selectedCharacterIndex: .constant(0), selectedSkill: .constant(nil), showSkillDetail: .constant(false), path: .constant(NavigationPath()))
}
