//
//  SplashView.swift
//  Abelito
//
//  Created by Karyna Budi Sanjaya on 20/05/25.
//

import SwiftUI

struct SplashView: View {
    @State private var isActive = false

    var body: some View {
        Group {
            if isActive {
                ContentView()
            } else {
                ZStack {
                    Color.black.ignoresSafeArea()

                    VStack {
                        Image("AbelNaruto") // your splash logo
                            .resizable()
                            .scaledToFit()
                            .frame(width: 200)

                        Text("All About Abelito")
                            .font(.custom("Ninja Naruto", size: 28))
                            .foregroundColor(.white)
                        
                        Text("The pictures in these app are generated by AI.")
                            .font(.custom("FOT-Reggae Std B", size: 12))
                    }
                }
                .onAppear {
                    // Delay before showing ContentView
                    DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {
                        withAnimation {
                            isActive = true
                        }
                    }
                }
                
            }
        }
    }
}
